create table  CUSTOMER_PERSONAL_INFO 
 -- CUSTOMER_PERSONAL_NO
(
CUSTOMER_ID varchar(5),
CUSTOMER_NAME  VARCHAR(30),
DATE_OF_BIRTH  date,
GUARDIAN_NAME VARCHAR(30),
MARTIAL_STATUS VARCHAR(10),
IDENTIFICATION_DOC_TYPE VARCHAR(20),
ID_DOC_NO VARCHAR(20),
CITIZENSHIP VARCHAR(10),
constraint CUST_PERS_INFO_PK primary key(Customer_id)
);

 -- CUSTOMER_REFRERENCE_NO
create  table CUSTOMER_REFRENCE_INFO
(
CUSTOMER_ID VARCHAR(5),
REFRENCE_ACC_NAME VARCHAR(20),
REFRENCE_ACC_NO   BIGINT(16),
REFRENCE_ACC_ADDRESS VARCHAR(20),
constraint CUST_REF_INFO_PK primary key(CUSTOMER_ID),
constraint CUST_REF_INFO_FK FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER_PERSONAL_INFO(CUSTOMER_ID)
);
show tables ;
 -- Bank_INFO
CREATE  TABLE BANK_INFO
(
IFSC_CODE  VARCHAR(15),
BANK_NAME  VARCHAR(25),
BRANCH_NAME VARCHAR(25),
constraint  BANK_INFO_PK primary key(IFSC_CODE)
);
show tables;
CREATE TABLE ACC_NO
(
ACC_NO  bigint(16),
CUSTOMER_ID VARCHAR(5),
ACC_TYPE    VARCHAR(10),
REGISTRATION_DATE  DATE,
ACTIVATION_DATE   DATE,
IFSC_CODE   varchar(20),
INTEREST  decimal(7,2),
INTIAL_DEPOSIT bigint(10),
constraint ACC_INFO_PK primary key(ACC_NO),
constraint ACC_INFO_PERS_FK  foreign key(CUSTOMER_ID)  references  CUSTOMER_PERSONAL_INFO(CUSTOMER_ID)
);
   show tables;
   -- Bank_inf0


INSERT INTO  BANK_INFO(IFSC_CODE,BANK_NAME ,BRANCH_NAME)values('SBIN0070695','SBI','GURUGRAM');
INSERT INTO  BANK_INFO(IFSC_CODE,BANK_NAME ,BRANCH_NAME)values('HDFCC000553','HDFC' ,'DELHI');
INSERT INTO  BANK_INFO(IFSC_CODE,BANK_NAME ,BRANCH_NAME)values('BARBOHAZARA','B0B','LUCKNOW');
INSERT INTO  BANK_INFO(IFSC_CODE,BANK_NAME ,BRANCH_NAME)values('UTIB0000278','AXIS BANK','DWARAKA');
INSERT INTO  BANK_INFO(IFSC_CODE,BANK_NAME ,BRANCH_NAME)values('ICICB007898','ICIC','PUNE');
 select * FROM BANK_INFO

-- CUSTOMER_PERSONAL_INFO
INSERT INTO CUSTOMER_PERSONAL_INFO(CUSTOMER_ID ,CUSTOMER_NAME , DATE_OF_BIRTH  ,GUARDIAN_NAME ,MARTIAL_STATUS ,IDENTIFICATION_DOC_TYPE ,ID_DOC_NO ,CITIZENSHIP)VALUES('C1','Mahesh kelkar','1972-06-02', 'dinkar kelkar','yes','FILE',123,'india');
INSERT INTO CUSTOMER_PERSONAL_INFO(CUSTOMER_ID ,CUSTOMER_NAME , DATE_OF_BIRTH  ,GUARDIAN_NAME ,MARTIAL_STATUS ,IDENTIFICATION_DOC_TYPE ,ID_DOC_NO ,CITIZENSHIP)VALUES('C2','Ramesh banerjee','1998-04-04','Arunima Banerjee','yes','pdf',456,'USA');
INSERT INTO CUSTOMER_PERSONAL_INFO(CUSTOMER_ID ,CUSTOMER_NAME , DATE_OF_BIRTH  ,GUARDIAN_NAME ,MARTIAL_STATUS ,IDENTIFICATION_DOC_TYPE ,ID_DOC_NO ,CITIZENSHIP)VALUES('C3','suesh tialk','1992-07-06', ' vinod tilak','yes','word doc',789,'UK');
INSERT INTO CUSTOMER_PERSONAL_INFO(CUSTOMER_ID ,CUSTOMER_NAME , DATE_OF_BIRTH  ,GUARDIAN_NAME ,MARTIAL_STATUS ,IDENTIFICATION_DOC_TYPE ,ID_DOC_NO ,CITIZENSHIP)VALUES('C4','RUCHIRA DIXIT','2001-06-11', 'Prasad dixit','NO','FILE',678,'UAE');
INSERT INTO CUSTOMER_PERSONAL_INFO(CUSTOMER_ID ,CUSTOMER_NAME , DATE_OF_BIRTH  ,GUARDIAN_NAME ,MARTIAL_STATUS ,IDENTIFICATION_DOC_TYPE ,ID_DOC_NO ,CITIZENSHIP)VALUES('C5','vijay Godbole','1980-03-02', ' tukaram godbole','yes','pdf','india');
select * from CUSTOMER_PERSONAL_INFO


-- CUSTOMER_REFRENCE_NO

insert into CUSTOMER_REFRENCE_INFO(CUSTOMER_ID ,REFRENCE_ACC_NAME ,REFRENCE_ACC_NO ,REFRENCE_ACC_ADDRESS,RELATION)VALUES('c1','MAHESH',764542,'345SBI',);
insert into CUSTOMER_REFRENCE_INFO(CUSTOMER_ID ,REFRENCE_ACC_NAME ,REFRENCE_ACC_NO ,REFRENCE_ACC_ADDRESS,RELATION)VALUES('C2','RAMESH',564738,'567HDFC','CUSTOM');
insert into CUSTOMER_REFRENCE_INFO(CUSTOMER_ID ,REFRENCE_ACC_NAME ,REFRENCE_ACC_NO ,REFRENCE_ACC_ADDRESS,RELATION)VALUES('C3','SUESH',987654,'453BOB','CUSTOM');
insert into CUSTOMER_REFRENCE_INFO(CUSTOMER_ID ,REFRENCE_ACC_NAME ,REFRENCE_ACC_NO ,REFRENCE_ACC_ADDRESS,RELATION)VALUES('C4','RUCHIRA',57830,'875AXIS','CUSTOM');

 select * from CUSTOMER_REFRENCE_INFO
  -- ACC NO
SELECT * FROM ACC_NO
 -- solving some queries
 --
 SELECT * from BANK_INFO
 WHERE BANK_NAME='SBI' AND BRANCH_NAME='GURUGRAM'

SELECT  CUSTOMER_ID FROM  CUSTOMER_PERSONAL_INFO
INNER JOIN  CUSTOMER_REFRENCE_INFO
ON CUSTOMER_PERSONAL_INFO.CUSTOMER_ID= CUSTOMER_REFRENCE_INFO.CUSTOMER_ID
 
 
 
